### PR TITLE
Removing messages log for production

### PR DESCRIPTION
**Pull request by Ghrisly**
In production, for a website, there can't be still log messages from the plugin. Even more if there's no problem.
For development, these messages can be re-opened for the debug, that's why they were left in comments.

### CODE REVIEW

**Comment by arnaudbreton** [comment]
Thanks for contributing!

I would personally prefer a cleaner solution, since we already use grunt / uglify-js, which will strip out console.\* in the minified version.

You could inspire from it: http://jstarrdewar.com/blog/2013/02/28/use-uglify-to-automatically-strip-debug-messages-from-your-javascript

What do you think?

**Comment by Ghrisly** [comment]
Yes, that would be cleaner indeed.
What about:
https://npmjs.org/package/grunt-strip ?

**Comment by arnaudbreton** [comment]
Never used this one; Did you ? 

If it's doing the job, without modifying all the plugin code, I'm definitely for it :).

**Comment by Ghrisly** [comment]
Nope, that's new for me too.
I've just tested it on my fork and it's doing great.

For now, in the Gruntfile, there is a strip task like this: 
strip : {
      main : {
        src : '<%= yeoman.dist %>/scripts/scripts.js',
        dest : '<%= yeoman.dist %>/scripts/scripts.js',
        options : {
          nodes : ['console.log', '$log.log']
        }
      }
    }

So, it doesn't remove the log.warn but i don't want to specify each case. That's why I'm trying to tell this package to remove all console.\* or log.*.

**Comment by Ghrisly** [comment]
That's stupid... I just had to tell it all the console and log, without any specific function.
And now it's ok.

**Comment by arnaudbreton** [comment]
It's OK for me. You managed to check that the minified version has no more logs?

**Comment by Ghrisly** [comment]
Yup.
(Except for the ones passed in arguments of course)

**Comment by arnaudbreton** [comment]
Perfect, OK to merge! Thanks again

**Comment by Ghrisly** [comment]
Nice.
Thanks for this project by the way. Using it at www.neo9.fr

**Comment by arnaudbreton** [comment]
Great! Thanks for the feedback and again the contribution. Really appreciate!

Just built and pushed last minified version. Ready to go :).

**Pull request merged**
