### PR TITLE
Correct path to main script

### PR DESCRIPTION
**Pull request by sdbondi**

### CODE REVIEW

**Comment by arnaudbreton** [comment]
Hi,

Thanks for this PR! I've just fixed the path and some few stuff (updated Karma, fixed jQuery path) so I can't merge it.
Meanwhile, I would be interested to hear from you about automatically update bower with the last rev id after `grunt build`. Any idea?

**Comment by sdbondi** [comment]
Ye wanted to look into that for this repo, but a simpler option might be to use a 'static' build path (so point to the built coffee without a revision in the filename) and let the developer run the uglification/rev task, or let tooling on the framework side take care of minification/uglification (for e.g. Rails' asset:precompile).

**Comment by larrybotha** [comment]
In order to go through source, we have to come to github and view the file here. Debugging an uglified script is more time consuming, too :tongue: 

It'd be useful to have an unminified version come down with bower, and also have its name the same as the name of your coffee file. I often see the uglified version added straight into `dist/` too - not essential, but it can be useful.

I'd also recommend taking a look at [grunt-bump](https://www.npmjs.org/package/grunt-bump) for quickly updating version numbers in bower and other locations.

**Comment by arnaudbreton** [comment]
Thanks for your insights. Would you be able to do a PR on that ? 
I'm not working on this project anymore for the moment and have few time to work on it.

**Comment by larrybotha** [comment]
I'll be happy to take a look when I get a few minutes!

**Comment by arnaudbreton** [comment]
Great, thanks! Do you think you'll find some time in the coming days? Otherwise, I'll push a release with your default offset fix before we fix this build issue.

**Comment by larrybotha** [comment]
nah, go ahead and make a release, I'll take a look in the coming weeks.

**Pull request closed without merging**
